### Business Problem
Our basic aim is to predict customer churn for a certain bank i.e. which customer is going to leave this bank service. Dataset is small(for learning purpose)and contains 10000 rows with 14 columns. 

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
dataset_new = dataset.drop(['Geography'], axis=1)

In [8]:
dataset_new.head()

RowNumber  CustomerId   Surname  CreditScore  Gender  Age  Tenure  \
0          1    15634602  Hargrave          619  Female   42       2   
1          2    15647311      Hill          608  Female   41       1   
2          3    15619304      Onio          502  Female   42       8   
3          4    15701354      Boni          699  Female   39       1   
4          5    15737888  Mitchell          850  Female   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   

   Exited  
0       1  
1       0  
2       1  
3       0  
4       0

In [9]:
X = dataset_new.iloc[:, 3:12].values
y = dataset_new.iloc[:, 12].values

In [10]:
X

array([[619, 'Female', 42, ..., 1, 1, 101348.88],
       [608, 'Female', 41, ..., 0, 1, 112542.58],
       [502, 'Female', 42, ..., 1, 0, 113931.57],
       ...,
       [709, 'Female', 36, ..., 0, 1, 42085.58],
       [772, 'Male', 42, ..., 1, 0, 92888.52],
       [792, 'Female', 28, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
import keras.models as km

Using TensorFlow backend.


In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
#Initializing Neural Network
classifier = Sequential()

In [17]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 9))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

In [18]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [19]:
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 60        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 109
Trainable params: 109
Non-trainable params: 0
_________________________________________________________________


In [22]:
from keras.utils import plot_model
import pydotplus 

In [23]:
import os     
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin'

In [24]:
# Fitting our model 
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 10)

Epoch 1/10
8000/8000 [==============================] - 3s 367us/step - loss: 0.4847 - accuracy: 0.7949
Epoch 2/10
8000/8000 [==============================] - 1s 179us/step - loss: 0.4247 - accuracy: 0.7969
Epoch 3/10
8000/8000 [==============================] - 1s 169us/step - loss: 0.4165 - accuracy: 0.8279
Epoch 4/10
8000/8000 [==============================] - 1s 168us/step - loss: 0.4110 - accuracy: 0.8335
Epoch 5/10
8000/8000 [==============================] - 1s 175us/step - loss: 0.4078 - accuracy: 0.8354
Epoch 6/10
8000/8000 [==============================] - 2s 191us/step - loss: 0.4055 - accuracy: 0.8361
Epoch 7/10
8000/8000 [==============================] - 1s 180us/step - loss: 0.4035 - accuracy: 0.8366
Epoch 8/10
8000/8000 [==============================] - 1s 172us/step - loss: 0.4026 - accuracy: 0.8366
Epoch 9/10
8000/8000 [==============================] - 1s 187us/step - loss: 0.4015 - accuracy: 0.8371
Epoch 10/10
8000/8000 [==============================] - 1s 175u

In [25]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [26]:
y_pred

array([[0.0919227 ],
       [0.07620859],
       [0.04184103],
       ...,
       [0.09561306],
       [0.24861321],
       [0.11836714]], dtype=float32)

In [27]:
import sklearn.metrics as metrics

In [28]:
metrics.roc_auc_score(y_test, y_pred)

0.7544065971435049

In [29]:
y_pred = (y_pred > 0.2)

In [30]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [31]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [32]:
cm

array([[1256,  348],
       [ 162,  234]], dtype=int64)

In [33]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.78      0.83      1604
           1       0.40      0.59      0.48       396

    accuracy                           0.74      2000
   macro avg       0.64      0.69      0.65      2000
weighted avg       0.79      0.74      0.76      2000

